### ISSUE TITLE
access code

### ISSUE THREAD

**Issue by flynnamy** [zhanxinrui/HDN#2]
Hi, it required the access code of this link:https://pan.baidu.com/s/1boKIoXGFOWZ-uu9X6WzDCA. Please share it, thanks! @zhanxinrui

**Comment by zhanxinrui** [comment]
> Hi, it required the access code of this link:https://pan.baidu.com/s/1boKIoXGFOWZ-uu9X6WzDCA. Please share it, thanks! @zhanxinrui

It’s ‘xaou’ and provided by POT(see in https://liangp.github.io/data/pot280/ in case they update the link) officially.
